% script to create K samples from distribution
% needs to be saved so that can recreate results
clear; close all;

% number of samples
N = 10^4;

% number of glaciers
load ../glaciers/glaciers.mat

% load K distribution from which to sample
% this comes from (is generated by) ../write_up/plots in makeplots.m
load Kdistribution_17feb.mat

% sample from distribution
% k = transpose(datasample(K,N*length(glaciers)));
rng('default'); % for reproducibility
k = random(K_pdf,N*length(glaciers),1);

% save
% leave commented so that don't accidently overwrite!
% save Ksamples.mat k
